# Generated by Django 3.0.8 on 2021-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehatagahiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientlog',
            name='Time',
        ),
        migrations.AddField(
            model_name='patientlog',
            name='DateTimeAdded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientlog',
            name='Message',
            field=models.TextField(max_length=500),
        ),
    ]
