# Generated by Django 3.0.8 on 2021-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehatagahiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkEmail', models.EmailField(max_length=64)),
            ],
        ),
    ]
