# Generated by Django 3.1.7 on 2021-03-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sehatagahiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('FilePath', models.CharField(max_length=64)),
                ('Type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sehatagahiapp.user')),
                ('Name', models.CharField(max_length=64)),
                ('FatherName', models.CharField(max_length=64)),
                ('DOB', models.DateField()),
                ('Area', models.CharField(max_length=64)),
                ('Gender', models.CharField(max_length=64)),
                ('MobileNumber', models.CharField(max_length=11)),
                ('ConditionTags', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='mobile_no',
            new_name='MobileNumber',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='email',
            new_name='WorkEmail',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='user',
            new_name='user_ID',
        ),
        migrations.AddField(
            model_name='therapist',
            name='SecurityQs1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='SecurityQs2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Items', models.ManyToManyField(to='sehatagahiapp.Item')),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Track', to='sehatagahiapp.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.CharField(max_length=64)),
                ('Notes', models.CharField(max_length=64)),
                ('Track_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PatientTrack', to='sehatagahiapp.track')),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PatientTrack', to='sehatagahiapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Progress', models.CharField(max_length=64)),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PatientTrack', to='sehatagahiapp.patienttrack')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=64)),
                ('Time', models.CharField(max_length=64)),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Log', to='sehatagahiapp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilePath', models.CharField(max_length=64)),
                ('user_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Data', to='sehatagahiapp.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='Therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Patients', to='sehatagahiapp.therapist'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Items', to='sehatagahiapp.therapist'),
        ),
    ]
