# Generated by Django 3.0.8 on 2021-04-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehatagahiapp', '0002_auto_20210424_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlog',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
