# Generated by Django 3.0.8 on 2021-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sehatagahiapp', '0002_auto_20210501_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttrack',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
